name: Deploy to Ionos

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - uses: actions/checkout@v3

      # Upload via SFTP
      - name: Upload to Ionos via SFTP
        uses: samkirkland/ftp-deploy-action@v4.3.6
        with:
          server: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USER }}
          password: ${{ secrets.IONOS_PASSWORD }}
          local-dir: dist/
          server-dir: /www/htdocs
